name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        ./build.sh
    - uses: actions/upload-artifact@v3
      with:
        name: ih8sn
        path: ih8sn-*.zip
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
          ih8sn-aarch64.zip
          ih8sn-uninstaller.zip
